cmake --no-warn-unused-cli \
    "-DLLVM_ENABLE_PROJECTS=mlir;clang;clang-tools-extra" \
    "-DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind" \
    -DCMAKE_INSTALL_PREFIX:STRING=install \
    -DLLVM_TARGETS_TO_BUILD:STRING=host \
    -DLLVM_ENABLE_ASSERTIONS:STRING=ON \
    -DLLVM_ENABLE_RTTI:STRING=ON \
    -DLLVM_ENABLE_ZLIB:STRING=OFF \
    -DLLVM_INCLUDE_TESTS:STRING=OFF \
    -DLLVM_INCLUDE_DOCS:STRING=OFF \
    -DLLVM_TOOL_LLVM_GO_BUILD:STRING=OFF \
    -DMLIR_BINDINGS_PYTHON_ENABLED:STRING=OFF \
    -DMLIR_INCLUDE_DOCS:STRING=OFF \
    -DMLIR_INCLUDE_TESTS:STRING=OFF \
    -DBUILD_SHARED_LIBS:STRING=ON \
    -DLLVM_TOOL_LLVM_LTO2_BUILD:STRING=OFF \
    -DLLVM_TOOL_LLVM_LTO_BUILD:STRING=OFF \
    -DLLVM_TOOL_LTO_BUILD:STRING=OFF \
    -DLLVM_INCLUDE_TOOLS:STRING=ON \
    -DLLVM_BUILD_TOOLS:STRING=ON \
    -DLLVM_INCLUDE_GO_TESTS:STRING=OFF \
    -DLLVM_INCLUDE_BENCHMARKS:STRING=OFF \
    -DLLVM_INCLUDE_UTILS:STRING=OFF \
    -DLLVM_ENABLE_OCAMLDOC:STRING=OFF \
    -DLLVM_ENABLE_THREADS:STRING=ON \
    -DLLVM_BUILD_EXAMPLES:STRING=ON \
    -DLLVM_INCLUDE_EXAMPLES:STRING=ON \
    -DLLVM_ENABLE_TERMINFO:STRING=OFF \
    -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
    -DCMAKE_BUILD_TYPE:STRING=Debug \
    -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-13 \
    -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-13 \
    -S/root/llvm-project/llvm \
    -B/root/llvm-project/build \
    -G Ninja

cmake --build \
    /root/llvm-project/build \
    --config Debug \
    --target all \
    -j $(grep -c ^processor /proc/cpuinfo) --
