# docker build -t riscv-gnu-toolchain:latest-llvm-musl -f riscv-gnu-toolchain/Dockerfile.llvm.musl .

FROM riscv-gnu-toolchain:latest-src

ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv

# riscv-gnu-toolchain
WORKDIR /home/riscv-gnu-toolchain
RUN ./configure --prefix=$RISCV --with-arch=rv64gc --with-abi=lp64d --enable-llvm
RUN make -j `nproc` musl
RUN make install

# clean src
WORKDIR /opt/riscv
RUN rm -rf /home/riscv-gnu-toolchain

# update PATH
ENV PATH="/opt/riscv/bin:${PATH}"
