# docker build -t iree_env:latest -f iree_llvm/Dockerfile.env .

# llvm is mounted in containers, eg: `docker run -v iree-llvm-project:/iree-llvm-project ...`
# llvm can be built by `./iree_llvm/llvm.sh`

FROM base:latest

ENV DEBIAN_FRONTEND=noninteractive

# make RUN commands use the new environment:
SHELL ["bash", "-l", "-c"]

RUN micromamba install numpy pybind11 -y

# extra tools
RUN micromamba install lit -y
RUN micromamba install nanobind -y

# optionl tools
RUN micromamba install fd-find ripgrep patchelf -y
