# docker build -t riscv-gnu-toolchain:latest-newlib -f riscv/Dockerfile.newlib .

FROM riscv-gnu-toolchain:latest-src

ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv

# newlib
WORKDIR /home/riscv-gnu-toolchain
RUN ./configure --prefix=$RISCV --with-arch=rv64gc --with-abi=lp64d
RUN make -j `nproc` newlib
RUN make install

# update PATH
ENV PATH="/opt/riscv/bin:${PATH}"
