# docker build -t riscv-gnu-toolchain:latest-llvm-glibc -f riscv/Dockerfile.llvm.glibc .

FROM riscv-gnu-toolchain:latest-src

ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv

# riscv-gnu-toolchain
WORKDIR /home/riscv-gnu-toolchain
RUN ./configure --prefix=$RISCV --with-arch=rv64gc --with-abi=lp64d --with-sim=spike --enable-llvm --enable-linux
RUN make -j `nproc` linux
RUN make install

# update PATH
ENV PATH="/opt/riscv/bin:${PATH}"
