# docker build -t riscv-gnu-toolchain:latest-gcc -f riscv/Dockerfile.gcc .

FROM riscv-gnu-toolchain:latest-src

ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv

# gcc with glibc
WORKDIR /home/riscv-gnu-toolchain
RUN ./configure --prefix=$RISCV --with-arch=rv64gc --with-abi=lp64d --enable-linux
RUN make -j `nproc` linux
RUN make install

# update PATH
ENV PATH="/opt/riscv/bin:${PATH}"
