# docker build -t riscv-gnu-toolchain:latest-newlib -f riscv/Dockerfile.newlib .

FROM riscv-gnu-toolchain:latest-src

ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv

# just newlib
WORKDIR /home/riscv-gnu-toolchain
RUN ./configure --prefix=$RISCV
RUN make -j `nproc`
RUN make install

# update PATH
ENV PATH="/opt/riscv/bin:${PATH}"
